<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Trax.Api.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Trax.Effect.Data.InMemory" />
    <PackageReference Include="Trax.Effect.Data.Postgres" />
    <PackageReference Include="Trax.Effect.Data.Sqlite" />
    <PackageReference Include="Trax.Effect.Provider.Json" />
    <PackageReference Include="Trax.Effect.Provider.Parameter" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Trax.Api/Trax.Api.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth/Trax.Api.Auth.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.ApiKey/Trax.Api.Auth.ApiKey.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.Jwt/Trax.Api.Auth.Jwt.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.Jwt.Cognito/Trax.Api.Auth.Jwt.Cognito.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.Jwt.Cognito.Issuer/Trax.Api.Auth.Jwt.Cognito.Issuer.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.Jwt.Testing/Trax.Api.Auth.Jwt.Testing.csproj" />
    <ProjectReference Include="../../src/Trax.Api.Auth.Oidc/Trax.Api.Auth.Oidc.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL/Trax.Api.GraphQL.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL.Audit/Trax.Api.GraphQL.Audit.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL.Client/Trax.Api.GraphQL.Client.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL.Client.Trax/Trax.Api.GraphQL.Client.Trax.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL.Client.Typed/Trax.Api.GraphQL.Client.Typed.csproj" />
    <ProjectReference Include="../../src/Trax.Api.GraphQL.PersistedOperations/Trax.Api.GraphQL.PersistedOperations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="GraphQLClient/**/*.graphql" />
  </ItemGroup>
</Project>
