using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Trax.Api.Extensions;
using Trax.Api.GraphQL.Extensions;
using Trax.Effect.Data.InMemory.Extensions;
using Trax.Effect.Extensions;
using Trax.Effect.Provider.Json.Extensions;
using Trax.Mediator.Extensions;

namespace Trax.Api.Tests.GraphQLClient.Fixtures;

/// <summary>
/// Spins up a real Trax GraphQL server in-process: <c>AddTrax</c> + <c>UseInMemory</c> +
/// <c>AddMediator</c> + <c>AddTraxGraphQL</c>. The schema is generated by
/// <c>TrainTypeModule</c> from <see cref="Trax.Api.Tests.GraphQLClient.Fakes"/> trains
/// decorated with <c>[TraxQuery(Namespace = "netsuiteClient")]</c>, so the response
/// envelope is the actual <c>discover.netsuiteClient.{field}</c> shape Trax emits —
/// not a hand-rolled HotChocolate type that merely models it.
///
/// No database required: the in-memory effect provider handles junction metadata and
/// parameter persistence in-process.
/// </summary>
public sealed class TraxServerFixture : IDisposable
{
    private readonly IHost _host;
    public TestServer Server { get; }
    public Uri BaseAddress { get; } = new("http://localhost/trax/graphql");

    public TraxServerFixture()
    {
        // AddTraxGraphQL disables introspection outside Development. The typed client
        // needs introspection to fetch the schema for query validation, so the fixture
        // forces Development to keep the round-trip working in tests.
        var hostBuilder = new HostBuilder()
            .UseEnvironment("Development")
            .ConfigureWebHost(web =>
            {
                web.UseTestServer();
                web.ConfigureServices(services =>
                {
                    services.AddLogging();
                    services.AddRouting();
                    // TrainAuthorizationService is wired by AddTraxApi and depends on
                    // IAuthorizationService. Development env enables strict DI validation,
                    // so register the authorization stack to satisfy the constructor.
                    // None of the trains under test are gated, so the policies stay empty.
                    services.AddAuthorization();

                    services.AddTrax(trax =>
                        trax.AddEffects(effects => effects.UseInMemory().AddJson())
                            .AddMediator(mediator =>
                                mediator
                                    .ScanAssemblies(typeof(TraxServerFixture).Assembly)
                                    // The test assembly also contains AuthE2E trains decorated
                                    // with [TraxAuthorize(Roles="Admin")]. This fixture does not
                                    // wire up ASP.NET auth, so opt out of the auth-service
                                    // presence check that would otherwise fail at host start.
                                    .AllowMissingAuthorizationService()
                            )
                    );

                    services.AddTraxApi();
                    services.AddTraxGraphQL();
                });
                web.Configure(app =>
                {
                    app.UseRouting();
                    app.UseEndpoints(endpoints =>
                    {
                        // AddTraxGraphQL registers the schema under the name "trax";
                        // the second arg of MapGraphQL selects that named schema.
                        endpoints.MapGraphQL("/trax/graphql", "trax");
                    });
                });
            });

        _host = hostBuilder.Start();
        Server = _host.GetTestServer();
    }

    public HttpClient CreateHttpClient()
    {
        var client = Server.CreateClient();
        client.BaseAddress = BaseAddress;
        return client;
    }

    public void Dispose()
    {
        _host.Dispose();
    }
}
